baseurl = "https://kimberlycherry.com"
languageCode = "en-us"
paginate = 6
summaryLength = "10"
theme = "parsa-hugo"
title = "Kym's Hugo Website"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
URL = ""
name = ""
weight = ""
[[menu.main]]
URL = "about"
name = "About"
weight = 2
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
author = "Kym Cherry"
author_image = "https://i.imgur.com/i4VTdN4.jpg"
bio = "I’m a Little Tea Pot."
copyright = "Copyright &copy; 2020 a theme by [themefisher.com](themefisher.com)"
description = "Home Page"
home = "Home"
layout = "1"
logo = "images/logo.png"
preloader = true
search = true
[params.instafeed]
access_token = "IGQVJXZAmVwYWp2cE5uS3RUeEJLdkVaTEJ4dVhDdWQ2MkNURlBZAc2t3OW5nZAXJxYS1NLXNIYlBnNkNnM1ZALMk5FT3Q3d2daejA2RnlWRWtmZAWtmQUJIdllHWm9XUGViUFU5ZAlpiZAXNaTWNtRDF1czlvTAZDZD"
enable = true
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/headroom/headroom.js"
[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.js"
[[params.plugins.js]]
link = "plugins/reading-time/readingTime.min.js"
[[params.plugins.js]]
link = "plugins/smooth-scroll/smooth-scroll.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.social]]
URL = "https://www.facebook.com/Studio-7th-Sanctuary-209342482447959/"
icon = "ti-facebook"
[[params.social]]
URL = "https://www.facebook.com/kcherryka"
icon = "ti-facebook"
[[params.social]]
URL = "https://twitter.com/kcherryka"
icon = "ti-twitter-alt"
[[params.social]]
URL = "https://www.instagram.com/kcherryka/"
icon = "ti-instagram"
[[params.social]]
URL = "https://www.youtube.com/user/kcherryka/"
icon = "ti-youtube"
